apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: |
    - rolearn: arn:aws:iam::793968663653:role/GitHubAction-AssumeRoleWithAction
      username: system:node:{{EC2PrivateDNSName}}
      groups:
  mapRoles: |
    - rolearn: arn:aws:iam::793968663653:role/GitHubAction-AssumeRoleWithAction
      username: system:node:{{EC2PrivateDNSName}}
      groups:

        - system:bootstrappers
        - system:nodes