apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::793968663653:user/github-simplebank
      username: github-ci
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::793968663653:role/GitHubAction-AssumeRoleWithAction
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes